source ./az_cli_utils.sh

LOCATION="eastus"
PREFIX="CES-DEV"
SSH_KEYFILE=/Users/ces/.ssh/azure_ansible_id_rsa.pub
OS_IMAGE="Ubuntu2204"
VM_SIZE="Standard_B1ls"
ALLOWED_VNETS=""

read -p "VMName: " NAME
read -p "Admin: " ADMIN_USER_NAME

SUBSCRIPTION_ID="CES-DEV"
BASE_NAME=$PREFIX-$NAME
echo $BASE_NAME
RESOURCEGROUP_NAME=$BASE_NAME-rg
VNET_NAME=$BASE_NAME-vnet
SUBNET_NAME=$BASE_NAME-subnet
PUBLICIP_NAME=$BASE_NAME-public-ip
NIC_NAME=$BASE_NAME-nic
VM_NAME=$BASE_NAME-VM0

create_rg $RESOURCEGROUP_NAME $LOCATION
create_vnet $RESOURCEGROUP_NAME $VNET_NAME $SUBNET_NAME
create_public_ip $RESOURCEGROUP_NAME $PUBLICIP_NAME
create_nic_public $RESOURCEGROUP_NAME $NIC_NAME $VNET_NAME $SUBNET_NAME $PUBLICIP_NAME
create_vm $RESOURCEGROUP_NAME $VM_NAME $LOCATION $OS_IMAGE $VM_SIZE $NIC_NAME $ADMIN_USER_NAME $SSH_KEYFILE
